baseURL = "https://sage-hamburg.github.io/"
languageCode = "de-de"
title = "SAGE Hamburg"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Lenz Grimmer"
    # ist riiiesig:
    #description = "SAGE Hamburg"
    description = ""
    githubUsername = "#"
    accent = "lightblue"
    showBorder = false
    backgroundColor = "white"
    # font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

# "uns" gibt es noch nicht
#[[menu.main]]
#    url = "/about/"
#    name = "Über uns"
#    weight = 2

[[menu.main]]
    url = "/aktuelles/"
    name = "Aktuelles"
    weight = 3

[[menu.main]]
    url = "/historisch/"
    name = "Historisches"
    weight = 3


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/sage-hamburg/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "fab fa-twitter"
    weight = 3
